version: '3.8'
services:
  python-app:
    build:
      context: ../../
      dockerfile: ./.devcontainer/docker/Dockerfile
      target: production
    env_file:
      - ../enviroment/production.env
    # command: sleep infinity
